//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Sync_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_INS_PLM1
    {
        public int DocEntry { get; set; }
        public int LineId { get; set; }
        public Nullable<int> VisOrder { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInst { get; set; }
        public string U_CatalgCode { get; set; }
        public string U_ItemName { get; set; }
        public string U_Brand { get; set; }
        public string U_SubBrand { get; set; }
        public string U_Remarks { get; set; }
        public string U_RowID { get; set; }
        public string U_Lock { get; set; }
        public string U_PrntName { get; set; }
        public string U_OodoCode { get; set; }
    }
}
