//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Sync_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_INS_OPLM
    {
        public int DocEntry { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<short> Instance { get; set; }
        public Nullable<int> Series { get; set; }
        public string Handwrtten { get; set; }
        public string Canceled { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInst { get; set; }
        public Nullable<int> UserSign { get; set; }
        public string Transfered { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> UpdateTime { get; set; }
        public string DataSource { get; set; }
        public string RequestStatus { get; set; }
        public string Creator { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> U_LstMdyDt { get; set; }
        public Nullable<System.DateTime> U_DocDate { get; set; }
        public string U_Remarks { get; set; }
        public string U_Status { get; set; }
        public string U_LstMdyBy { get; set; }
        public string U_ItemCode { get; set; }
        public string U_ItemName { get; set; }
        public string U_ModBy { get; set; }
        public string U_ItemGrp { get; set; }
        public string U_Size { get; set; }
        public string U_Style { get; set; }
        public string U_UserSign { get; set; }
        public Nullable<decimal> U_PurPrice { get; set; }
        public string U_ItmGrpCd { get; set; }
        public string U_PriLstNa { get; set; }
        public string U_BaseList { get; set; }
        public Nullable<decimal> U_SalFact { get; set; }
        public Nullable<decimal> U_PurFact { get; set; }
        public Nullable<System.DateTime> U_EffDate { get; set; }
        public string U_PreparedBy { get; set; }
        public string U_PreBy { get; set; }
    }
}
