//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Sync_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_INS_PLM2
    {
        public int DocEntry { get; set; }
        public int LineId { get; set; }
        public Nullable<int> VisOrder { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInst { get; set; }
        public string U_State { get; set; }
        public string U_RowID { get; set; }
        public Nullable<decimal> U_MRP { get; set; }
        public Nullable<decimal> U_SelPrice { get; set; }
        public Nullable<decimal> U_Dirprice { get; set; }
        public Nullable<decimal> U_Franprice { get; set; }
        public string U_Remarks { get; set; }
        public Nullable<decimal> U_OMRP { get; set; }
        public Nullable<decimal> U_OSelPrice { get; set; }
        public Nullable<decimal> U_ODirprice { get; set; }
        public Nullable<decimal> U_OFranprice { get; set; }
        public Nullable<decimal> U_DirMRP { get; set; }
        public Nullable<decimal> U_FranMRP { get; set; }
        public Nullable<decimal> U_ODirMRP { get; set; }
        public Nullable<decimal> U_OFranMRP { get; set; }
        public Nullable<decimal> U_OffMRP { get; set; }
    }
}
