//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Sync_Api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RRLiveEntities : DbContext
    {
        public RRLiveEntities()
            : base("name=RRLiveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_INS_OPLM> C_INS_OPLM { get; set; }
        public virtual DbSet<C_INS_PLM1> C_INS_PLM1 { get; set; }
        public virtual DbSet<C_INS_PLM2> C_INS_PLM2 { get; set; }
    }
}
